### ISSUE TITLE
Implementation of FFieldPathProperty

### ISSUE THREAD

**Issue by narknon** [atenfyr/UAssetAPI#31] opened 2022-10-12 15:41 UTC
**Is your feature request related to a problem? Please describe.**

Property isn't parsed.

**Describe the solution you'd like**
Implement/parse the property.

**Describe alternatives you've considered**
Maybe trying to implement it myself.

**Additional context**

![image](https://user-images.githubusercontent.com/73571427/195387482-7c816b1b-9db0-4973-9fa6-63f3f0cb400d.png)

[Secondary.zip](https://github.com/atenfyr/UAssetAPI/files/9766557/Secondary.zip)

**Comment by atenfyr** [comment] 2022-10-29 23:45
Duplicate of #22

**Closed by atenfyr** 2022-10-29 23:45 UTC
