### ISSUE TITLE
Failed to maintain binary equality!

### ISSUE THREAD

**Issue by LievreAI** [atenfyr/UAssetAPI#37] opened 2022-11-02 20:02 UTC
@atenfyr 
i have a game called "sword art online fatal bullet"
try to open file attached
game engine : unreal engine 4.17

i have an error say "Failed to maintain binary equality! UassetAPI may not be able to parse this particular asset correctly , and you may not be able to load this file in-game if modified
Assets : 
[AVID.zip](https://github.com/atenfyr/UAssetAPI/files/9923797/AVID.zip)

**Comment by atenfyr** [comment] 2022-11-03 02:10
I would appreciate it if you tried to not waste my time ;)

Duplicate of atenfyr/UAssetGUI#39

**Closed by atenfyr** 2022-11-03 02:10 UTC
