### ISSUE TITLE
Cannot change bIsEnabled value

### ISSUE THREAD

**Issue by oureveryday** [atenfyr/UAssetAPI#27] opened 2022-08-06 07:52 UTC
**Describe the bug**
Changed .uasset data bIsEnabled to true and packed file using unrealpak. But bIsEnabled is still false in the FModel.
When load .uasset "Failed to parse 11 exports!" happens,and modified .uasset causes game crash.

**Screenshots**

![179390673-81c9dfc6-b284-4a8d-b5b4-b6ef87204195](https://user-images.githubusercontent.com/20489787/183240024-de921852-e159-4d39-91d7-54aeebb1ece5.jpg)
![179390476-c4c81b56-b239-43ca-ad13-f111794e12f1](https://user-images.githubusercontent.com/20489787/183240059-28abcb95-d2c2-4b10-b7f5-82e0c8fa7566.jpg)
![179390478-109e36f2-20ee-4415-b48e-b2fdf27b16eb](https://user-images.githubusercontent.com/20489787/183240033-1c13a5da-19a5-4313-9346-adfd18f8d2d2.jpg)
(After Modified)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v1.0.0.0-alpha.6 (https://github.com/atenfyr/UAssetGUI/commit/ebcdfce4c4aeb4132cef7061f47f87fea4de6f73)
 - Game: Sword and Fairy 7
 - Game UE4 version: 4.25
 - File: Pal7\Content\UI\UMG\System\UMG_Photo.uasset

**Additional context**
[UMG_Photo.zip](https://github.com/atenfyr/UAssetGUI/files/9127265/UMG_Photo.zip)

**Comment by atenfyr** [comment] 2022-08-09 21:46
Duplicate of atenfyr/UAssetGUI#30

**Closed by atenfyr** 2022-08-09 21:46 UTC
